- name: OpenStack preflight - Setup kolla-ansible
  ansible.builtin.import_playbook: preflight.yml

- name: Ceph Integration
  ansible.builtin.import_playbook: ceph-integrate.yml

- name: OpenStack deployment
  ansible.builtin.import_playbook: deploy.yml

- name: OpenStack post-deploy
  ansible.builtin.import_playbook: post-deploy.yml
