---
- name: Create CephFS pools and filesystem
  hosts: ceph_admin
  become: true
  gather_facts: false
  tasks:
    - name: Create CephFS metadata pool
      ceph.automation.ceph_pool:
        name: cephfs-meta
        pool_type: replicated
        size: "3"
        rule_name: replicated_ssd
        application: cephfs

    - name: Create CephFS data pool
      ceph.automation.ceph_pool:
        name: cephfs-data-ssd
        pool_type: erasure
        rule_name: ssd-ec42
        erasure_profile: ssd-ec42
        application: cephfs

    - name: Create mycephfs filesystem
      ceph.automation.ceph_fs:
        name: mycephfs
        metadata: cephfs-meta
        data: cephfs-data-ssd
        max_mds: 3
