- name: Create CRUSH rules and EC profile
  hosts: ceph_admin
  become: true
  gather_facts: false
  vars:
    osd_wait_retries: 60
    osd_wait_delay: 5
  tasks:
    - name: Create ssd EC42 erasure-code profile
      ceph.automation.ceph_ec_profile:
        name: ssd-ec42
        k: "4"
        m: "2"
        crush_device_class: ssd
        crush_failure_domain: host
        force: true
      register: ssd_ec_profile
      until: ssd_ec_profile.rc == 0
      retries: "{{ osd_wait_retries }}"
      delay: "{{ osd_wait_delay }}"

    - name: Create ssd EC42 erasure CRUSH rule
      ceph.automation.ceph_crush_rule:
        name: ssd-ec42
        rule_type: erasure
        profile: ssd-ec42
      register: ssd_ec_rule
      until: ssd_ec_rule.rc == 0
      retries: "{{ osd_wait_retries }}"
      delay: "{{ osd_wait_delay }}"

    - name: Create replicated CRUSH rule for HDD
      ceph.automation.ceph_crush_rule:
        name: replicated_hdd
        rule_type: replicated
        bucket_root: default
        bucket_type: host
        device_class: hdd
      register: replicated_hdd_rule
      until: replicated_hdd_rule.rc == 0
      retries: "{{ osd_wait_retries }}"
      delay: "{{ osd_wait_delay }}"

    - name: Create replicated CRUSH rule for SSD
      ceph.automation.ceph_crush_rule:
        name: replicated_ssd
        rule_type: replicated
        bucket_root: default
        bucket_type: host
        device_class: ssd
      register: replicated_ssd_rule
      until: replicated_ssd_rule.rc == 0
      retries: "{{ osd_wait_retries }}"
      delay: "{{ osd_wait_delay }}"

    - name: Create hdd EC42 erasure-code profile
      ceph.automation.ceph_ec_profile:
        name: hdd-ec42
        k: "4"
        m: "2"
        crush_device_class: hdd
        crush_failure_domain: host
        force: true
      register: hdd_ec_profile
      until: hdd_ec_profile.rc == 0
      retries: "{{ osd_wait_retries }}"
      delay: "{{ osd_wait_delay }}"

    - name: Create hdd EC42 erasure CRUSH rule
      ceph.automation.ceph_crush_rule:
        name: hdd-ec42
        rule_type: erasure
        profile: hdd-ec42
      register: hdd_ec_rule
      until: hdd_ec_rule.rc == 0
      retries: "{{ osd_wait_retries }}"
      delay: "{{ osd_wait_delay }}"

    # This one's crush failure domain is osd only because i don't have enough resource for 11+ nodes ceph cluster
    - name: Create hdd EC83 erasure-code profile
      ceph.automation.ceph_ec_profile:
        name: hdd-ec83
        k: "8"
        m: "3"
        crush_device_class: hdd
        crush_failure_domain: osd
        force: true
      register: hdd_ec_profile
      until: hdd_ec_profile.rc == 0
      retries: "{{ osd_wait_retries }}"
      delay: "{{ osd_wait_delay }}"

    - name: Create hdd EC83 erasure CRUSH rule
      ceph.automation.ceph_crush_rule:
        name: hdd-ec83
        rule_type: erasure
        profile: hdd-ec83
      register: hdd_ec_rule
      until: hdd_ec_rule.rc == 0
      retries: "{{ osd_wait_retries }}"
      delay: "{{ osd_wait_delay }}"
