---
- name: Ceph preflight
  hosts: ceph
  become: true
  gather_facts: true
  tasks:
    - name: Install prerequisites
      ansible.builtin.apt:
        name: [cephadm, chrony, ceph-common]
        state: present
        update_cache: true
    - name: Ensure chrony is running
      ansible.builtin.service:
        name: chrony
        state: started
        enabled: true
