[rgw]
ceph-node1 ansible_host=10.10.30.11 ansible_user=openstack
ceph-node2 ansible_host=10.10.30.12 ansible_user=openstack
ceph-node3 ansible_host=10.10.30.13 ansible_user=openstack
ceph-node4 ansible_host=10.10.30.14 ansible_user=openstack
ceph-node5 ansible_host=10.10.30.15 ansible_user=openstack
ceph-node6 ansible_host=10.10.30.16 ansible_user=openstack
ceph-node7 ansible_host=10.10.30.17 ansible_user=openstack
ceph-node8 ansible_host=10.10.30.18 ansible_user=openstack
ceph-node9 ansible_host=10.10.30.19 ansible_user=openstack
