---
- name: Sync keystone password
  hosts: rgw
  become: true
  vars:
    password_file_src: "files/keystone_admin_password"   # Relative path
    password_file_dest: "/etc/ceph/keystone_admin_password"
    owner: "openstack"
    group: "openstack"
    mode: "0600"

  tasks:
    - name: Make dir if not exist
      file:
        path: /etc/ceph
        state: directory
        owner: "{{ owner }}"
        group: "{{ group }}"
        mode: 0755

    - name: Copy
      copy:
        src: "{{ password_file_src }}"
        dest: "{{ password_file_dest }}"
        owner: "{{ owner }}"
        group: "{{ group }}"
        mode: "{{ mode }}"
        backup: yes

    - name: Destination
      stat:
        path: "{{ password_file_dest }}"
      register: result

    - name: Finish
      debug:
        msg: "Finished {{ inventory_hostname }}"
      when: result.stat.exists
