[DEFAULT]
enabled_backends = ssd, hdd
default_volume_type = HDD

[ssd]
volume_driver = cinder.volume.drivers.rbd.RBDDriver
volume_backend_name = ssd
rbd_pool = volumes-ssd-meta
rbd_ceph_conf = /etc/ceph/ceph-ssd.conf
rados_connect_timeout = 5
rbd_user = cinder
rbd_cluster_name = ceph-ssd
rbd_keyring_conf = /etc/ceph/ceph-ssd.client.cinder.keyring
rbd_secret_uuid = df45e2b5-140a-469c-bb1e-686b76c29aa4
report_discard_supported = true

[hdd]
volume_driver = cinder.volume.drivers.rbd.RBDDriver
volume_backend_name = hdd
rbd_pool = volumes-hdd
rbd_ceph_conf = /etc/ceph/ceph-hdd.conf
rados_connect_timeout = 5
rbd_user = cinder
rbd_cluster_name = ceph-hdd
rbd_keyring_conf = /etc/ceph/ceph-hdd.client.cinder.keyring
rbd_secret_uuid = df45e2b5-140a-469c-bb1e-686b76c29aa4
report_discard_supported = true
