[ceph-node]
ceph-node4 ansible_host=10.10.30.14 ansible_user=openstack
ceph-node5 ansible_host=10.10.30.15 ansible_user=openstack
ceph-node6 ansible_host=10.10.30.16 ansible_user=openstack
ceph-node7 ansible_host=10.10.30.17 ansible_user=openstack
ceph-node8 ansible_host=10.10.30.18 ansible_user=openstack
ceph-node9 ansible_host=10.10.30.19 ansible_user=openstack
ceph-node10 ansible_host=10.10.30.20 ansible_user=openstack
