version: 2
ethernets:
  ens3: # mgmt
    dhcp4: true
    dhcp6: false
  ens4: # ceph pub
    dhcp4: false
    dhcp6: false
    addresses: [10.10.2.10/24]
  ens5: # os internal
    dhcp4: false
    dhcp6: false
    addresses: [10.10.3.10/24]
  ens6: # os external
    dhcp4: false
    dhcp6: false
    addresses: [10.10.4.10/24]
  ens7: # os tenant/neutron
    dhcp4: false
    dhcp6: false
