- name: Generate SSH key pair
  hosts: ceph_admin
  become: true
  tasks:
    - name: Generate SSH key pair
      community.crypto.openssh_keypair:
        path: /root/.ssh/id_ed25519
        type: ed25519
    - name: Read public key
      slurp:
        src: /root/.ssh/id_ed25519.pub
      register: admin_pub_key
- name: Distribute SSH key pair
  hosts: ceph
  become: true
  tasks:
    - name: Add admin public key to authorized_key of all nodes
      authorized_key:
        user: root
        state: present
        key: "{{ hostvars[groups['ceph_admin'][0]]['admin_pub_key']['content'] | b64decode }}"
- name: Ceph preflight
  hosts: ceph
  become: true
  tasks:
    - name: Install prerequisites
      apt:
        name: [cephadm, chrony]
        state: present
        update_cache: true
    - name: Ensure chrony is running
      service:
        name: chrony
        state: started
        enabled: true
