- name: Clone cephadm-ansible, generate SSH key pair
  hosts: ceph_admin
  become: true
  tasks:
    - name: Install depedencies
      apt:
        name: [git, python3-pip]
        state: present
        update_cache: yes
    - name: Clone repository
      git:
        repo: https://github.com/ceph/cephadm-ansible.git
        dest: /root/cephadm-ansible
    - name: Copy inventory from host
      copy:
        src: ./../ceph_inventory.ini
        dest: /root/cephadm-ansible/hosts
    - name: Generate SSH key pair
      shell: ssh-keygen -t ed25519 -f /root/.ssh/id_ed25519 -N ""
      args:
        creates: /root/.ssh/id_ed25519
    - name: Read public key
      shell: cat /root/.ssh/id_ed25519.pub
      register: admin_pub_key
- name: Distribute SSH key pair
  hosts: ceph
  become: true
  tasks:
    - name: Add admin public key to authorized_key of all nodes
      authorized_key:
        user: root
        state: present
        key: "{{ hostvars[groups['ceph_admin'][0]]['admin_pub_key']['stdout'] }}"
